# Site settings
name: Q-Canon
subtitile: Notes on Quantum Information Science
author: WXM
# url: "https://WXMpublic.github.io/" # the base hostname & protocol for your site
url: # serve locally
baseurl: "/Blog/" # the subpath of your site, e.g. blog/
description: >
  A fresh start up of Git Pages
banner: Information is physical
cover: "_assets/header/header_image.jpg"
logo: "styles/images/favicon.ico"
about: "about/"

permalink: :categories/:title/
# permalink: /:year/:month/:day/:title/
# paginate: 10

collections:

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

figure_url: "/Blog/asserts/figures/"
resume_site: "https://WXMpublic.github.io/New-Page/about/"
github: "https://github.com/WXMpublic/"

# Build settings
# markdown: kramdown