# Site settings
name: Q-Canon
subtitile: Notes on Quantum Information Science
author: WXM
# url: "https://WXMpublic.github.io/" # the base hostname & protocol for your site
url: # serve locally
baseurl: "/Blog/" # the subpath of your site, e.g. blog/
description: >
  Notes on the basics of quantum information
banner: Information is physical
cover: "_assets/header/header_image.jpg"
logo: "assets/logo/favicon.ico"
figure_url: "/Blog/assets/images/"
about: "about/"

# sass:
#   sass_dir: _sass

permalink: :categories/:title/
# permalink: /:year/:month/:day/:title/
# paginate: 10

collections:

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

resume_site: "https://WXMpublic.github.io/Blog/about/"
github: "https://github.com/WXMpublic/"

# Build settings
# markdown: kramdown